version: '3'
services: 
    api:
        build: './api'
        ports: 
            - "8000:8000"
    web:
        build: './web'
        ports:
            - "3000:3000"
    nginx:
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
            - ./web/public:/srv/www/static
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web
            - api