# Generated by Django 3.0.3 on 2020-02-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
