# Generated by Django 3.0.3 on 2020-02-20 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('authentication', '0002_auto_20200220_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.Token')),
                ('refreshed', models.DateTimeField(auto_now_add=True, verbose_name='Refreshed')),
            ],
            options={
                'verbose_name': 'Expiring Token',
                'verbose_name_plural': 'Expiring Tokens',
            },
            bases=('authtoken.token',),
        ),
    ]
