# Generated by Django 3.0.3 on 2020-07-04 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_auto_20200704_1641"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediaaccount",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="social_media_account",
                to="authentication.Profile",
            ),
        ),
    ]
