# Generated by Django 3.0.3 on 2020-07-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_profile_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainableDevelopmentGoals',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='sdgs',
            field=models.ManyToManyField(related_name='profiles', to='authentication.SustainableDevelopmentGoals'),
        ),
    ]
