# Generated by Django 3.0.7 on 2020-09-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0018_auto_20200823_1953"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_junior_fellow",
            field=models.BooleanField(default=False),
        ),
    ]
