# Generated by Django 3.0.7 on 2020-09-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20200923_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_junior_fellow',
            field=models.BooleanField(),
        ),
    ]
