# Generated by Django 3.0.3 on 2020-10-03 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_auto_20200924_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_account', to='authentication.Profile'),
        ),
    ]
