# Generated by Django 3.0.3 on 2020-09-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_storeitem_preview_image'),
        ('store', '0003_auto_20200920_1543'),
    ]

    operations = [
    ]
