# Generated by Django 3.0.3 on 2020-07-19 09:03

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, help_text='Add a short text describing the post', verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Write content of post in markdown. To add images, drag and drop them onto the content text field.'),
        ),
    ]
