# Generated by Django 3.0.3 on 2020-08-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_auto_20200719_1433"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-updated"]},
        ),
        migrations.AddField(
            model_name="post",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Preview image for the post",
                upload_to="post-previews",
            ),
        ),
    ]
