name: docker image build and push
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build-push:
    # Job name is Greeting
    name: docker build-push
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # This step uses docker's github action: https://github.com/marketplace/actions/build-and-push-docker-images
      # Setting up the .env file first
      - shell: bash
        env:
          GAUTH_CLIENT_ID: ${{ secrets.GAUTH_CLIENT_ID }}
        run: 'echo "GAUTH_CLIENT_ID=GAUTH_CLIENT_ID" > app/api/.env'
      - shell: bash
        env:
          GAUTH_CLIENT_SECRET: ${{ secrets.GAUTH_CLIENT_SECRET }}
        run: 'echo "GAUTH_CLIENT_SECRET=GAUTH_CLIENT_SECRET" >> app/api/.env'
      # Push docker image to dockerhub after building
      - name: docker-build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: meltondevops/melton-app-server
          tags: latest
          path: ./app
  ansible-deploy:
    name: ansible deploy
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - shell: bash
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          eval "$(ssh-agent -s)"
#          mkdir ~/.ssh
          ssh-add - <<< "${DEPLOY_KEY}"
#          chmod 600 ~/.ssh/id_rsa
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible==2.9.2 requests
      - name: test SSH
        run: |
          echo $(ssh -o BatchMode=yes -o ConnectTimeout=5 root@85.214.65.195 echo ok 2>&1)
          cat ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa | base64
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: 85.214.65.195
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            whoami
            ls -al
      - name: test ansible host ping
        run: |
          ansible-inventory -i ./.github/ansible/hosts --list -y
          ansible -i ./.github/ansible/hosts all  -m ping -u root -vvv