name: docker image build and push
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build-push:
    # Job name is Greeting
    name: docker build-push
    on:
      push:
        tags:
          - 'v*.*.*'
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # This step uses docker's github action: https://github.com/marketplace/actions/build-and-push-docker-images
      # Setting up the .env file first
      - shell: bash
        env:
          GAUTH_CLIENT_ID: ${{ secrets.GAUTH_CLIENT_ID }}
        run: 'echo "GAUTH_CLIENT_ID=GAUTH_CLIENT_ID" > app/api/.env'
      - shell: bash
        env:
          GAUTH_CLIENT_SECRET: ${{ secrets.GAUTH_CLIENT_SECRET }}
        run: 'echo "GAUTH_CLIENT_SECRET=GAUTH_CLIENT_SECRET" >> app/api/.env'
      # Push docker image to dockerhub after building
      - name: docker-build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: meltondevops/melton-app-server
          tags: latest
          path: ./app
  ansible-deploy:
    name: ansible deploy
    on:
      push:
        tags:
          - 'v*.*.*'
    needs: build-push
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - shell: bash
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.DEPLOY_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          echo "${GITHUB_REF:10}"
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible==2.9.2 requests
      - name: test ansible host ping
        run: |
          echo "${GITHUB_REF:10}"
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-inventory -i ./.github/ansible/hosts --list -y
          ansible -i ./.github/ansible/hosts all  -m ping -u root -vvv
          ansible-playbook -i ./.github/ansible/hosts ./.github/ansible/docker_playbook.yml