name: docker image build and push
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build-push:
    # Job name is Greeting
    name: docker build-push
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # This step uses docker's github action: https://github.com/marketplace/actions/build-and-push-docker-images
      - shell: bash
        env:
          GAUTH_CLIENT_ID: ${{ secrets.GAUTH_CLIENT_ID }}
        run: 'echo "GAUTH_CLIENT_ID=GAUTH_CLIENT_ID" > app/api/.env'
      - shell: bash
        env:
          GAUTH_CLIENT_SECRET: ${{ secrets.GAUTH_CLIENT_SECRET }}
        run: 'echo "GAUTH_CLIENT_SECRET=GAUTH_CLIENT_SECRET" >> app/api/.env'
      - name: docker-build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: meltondevops/melton-app-server
          tags: latest
          path: ./app